# Model arguments
# model_init_kwargs:
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
trust_remote_code: true
attn_implementation: flash_attention_2  #sdpa
# use_peft: True

# Data training arguments
system_prompt: SYSTEM_PROMPT_DEBATE
dataset_mixer:
  "data/final_train_dict_LConf_qwen25_7B": 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 1
truncation_side: "left"
padding_side: "left"
wandb_project: "MAS"

# GRPO trainer config
# Output and Run Configuration
output_dir: /home/ubuntu/mj/MAS/saved/grpo-qwen25-7b-MAS-DS-DR-LConf
overwrite_output_dir: true
run_name: grpo-qwen25-7b-MAS-DS-DR-LConf
report_to:
  - wandb
save_strategy: "steps"
save_steps: 50
save_only_model: true
save_total_limit: 10
# resume_from_checkpoint: true

# Training Configuration
num_train_epochs: 1
max_steps: -1
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 3.0e-06
optim: adamw_torch
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 1.0
seed: 42
shuffle_dataset: false
bf16: true
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
beta: 0.04
num_iterations: 4
epsilon: 0.2
epsilon_high: 0.28
scale_rewards: true
loss_type: grpo
mask_truncated_completions: true
use_liger_loss: false

# Evaluation Configuration
per_device_eval_batch_size: 16
eval_strategy: "steps"
eval_steps: 50
eval_on_start: true

# Logging Configuration
logging_first_step: true
log_level: info
logging_steps: 10
logging_strategy: steps
log_completions: true
num_completions_to_print: 2
wandb_log_unique_prompts: true

# Generation Configuration
disable_dropout: true
max_prompt_length: 32768
max_completion_length: 2048 #8192
num_generations: 8
temperature: 0.9
top_p: 1.0
top_k: 50
repetition_penalty: 1.0
use_vllm: True
vllm_server_host: "0.0.0.0"
vllm_server_port: 8000
# vllm_guided_decoding_regex: <think>\n(.*?)\n</think>\n\n<answer>\n(.*?)\n</answer> 